### ISSUE TITLE
Where does workshops go?

### ISSUE THREAD

**Issue by naher94** [c0deLab/tech.soa.cmu.edu#19]

**Comment by naher94** [comment]
@eddymankim what data do we expect to have for a workshop?

Name, Date / Time, Registration URL? 

Other things?

**Comment by eddymankim** [comment]
Front Matter:
Workshop Title (e.g. Policies & Laser Cutting – Group A)
Additional Description (e.g. dFab Lab general policies introduction, laser cutter training, REQUIRED prerequisite for other dFab workshops)
Start Date / Time
End Date / Time
Registration URL
Category (e.g. Digital Fabrication)
Instructor(s)
Location

Content:
Blog post of workshop attendance requirements (e.g. laptops, software), prerequisites, contents (e.g. slides link), links and other content

Here's the latest schedule that I will be populating from: https://docs.google.com/a/andrew.cmu.edu/spreadsheets/d/1yYnOXTSs_OvZsEgDGLORk6oPPR5LpZKbH979n5UrbTk/edit?usp=sharing

**Comment by naher94** [comment]
ok awesome @eddymankim I have set up a test file in the workshop collection, and will be setting it on on the rest of the pages later on this weekend

**Comment by naher94** [comment]
resolved

**Comment by naher94** [comment]
Location not handled yet and data on the post page

**Comment by naher94** [comment]
Redesign workshop tile with this added info
reference #34

**Comment by naher94** [comment]
Build Error a result of this

**Comment by naher94** [comment]
Resolved Minus Build Error
