### ISSUE TITLE
Hover Effect for Link Icon

### ISSUE THREAD

**Issue by naher94** [c0deLab/tech.soa.cmu.edu#32]

**Comment by naher94** [comment]
@eddymankim would you mind taking a look at this one?

**Comment by eddymankim** [comment]
@naher94 I think a simple foundation button labeled "Register" should suffice.

**Comment by naher94** [comment]
@eddymankim do you think the icon is unclear? Designed a couple options but did like the other ones as much
![screen shot 2017-08-06 at 2 09 20 am](https://user-images.githubusercontent.com/7800629/29001051-4a0d1264-7a4c-11e7-9ec1-c76d98c6ddbb.png)

**Comment by eddymankim** [comment]
The top one with "Register" is good. Don't want to take any chances with icons. Also sometimes there might not be a register link, in which case the button should disappear.

**Comment by naher94** [comment]
ok sounds good, I'll add an if to handle that case

**Comment by naher94** [comment]
Resolved
