### ISSUE TITLE
Workshop page tweaks

### ISSUE THREAD

**Issue by eddymankim** [c0deLab/tech.soa.cmu.edu#34]
I don't think there needs to be an excerpt of the workshop posts. It might be better for 'details' to take place of where the excerpt was but with smaller font.

**Comment by naher94** [comment]
will details be more than a word or 2?

**Comment by eddymankim** [comment]
Most likely. We want to be flexible with this one. Sometimes there's no detail, sometimes just enough detail to highlight important info such as prerequisites, sometimes something more spelled out, etc.
